In [1]:
import numpy as np
from scipy import signal


In [7]:
a=np.random.random_integers(5,100,size=(4,5))
b=np.random.random_integers(5,100,size=(3,2))

/Users/viveksingal/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(5, 100 + 1) instead
  """Entry point for launching an IPython kernel.
/Users/viveksingal/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(5, 100 + 1) instead
  


In [9]:
f = open("input.txt", "w")
f.write(" ".join(str(num) for num in a.shape))
f.write(" ")
for elem in a:
    f.write(" ".join(str(num) for num in elem))
    f.write(" ")
f.write(" ".join(str(num) for num in b.shape))
f.write(" ")
for elem in b:
    f.write(" ".join(str(num) for num in elem))
    f.write(" ")
f.close()

f=open("outputPython.txt","w")
c=signal.correlate2d(a,b,mode="valid")
for elem in c:
    f.write(" ".join(str(num) for num in elem))
    f.write(" ")
f.close()

In [11]:
c

array([[15319, 15590, 17400, 15873],
       [13773, 17529, 21062, 16079]])

In [9]:
a

array([[45, 57, 37, 95, 71],
       [11, 48, 85, 83, 66],
       [38, 29, 23, 16, 53],
       [57, 15, 90, 65, 40]])

In [10]:
b

array([[66, 39],
       [97, 17],
       [64,  8]])